"""add qr_code_url to museums

Revision ID: 1f24b62d5fa2
Revises: a1b2c3d4e5f6
Create Date: 2026-04-20 09:39:13.675718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f24b62d5fa2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('countries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('museums', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('museums', 'qr_code_url')
    op.alter_column('countries', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cities', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
