"""create exhibits

Revision ID: 81ade7fee947
Revises: b0d5b2085f6a
Create Date: 2026-04-12 12:14:36.493813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ade7fee947'
down_revision: Union[str, None] = 'b0d5b2085f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('museum_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='exhibitstatus'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('listens_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibits_hall_id'), 'exhibits', ['hall_id'], unique=False)
    op.create_index(op.f('ix_exhibits_museum_id'), 'exhibits', ['museum_id'], unique=False)
    op.create_index(op.f('ix_exhibits_slug'), 'exhibits', ['slug'], unique=True)
    op.create_table('exhibit_audio_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exhibit_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('uz', 'ru', 'en', name='languagecode'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibit_audio_tracks_exhibit_id'), 'exhibit_audio_tracks', ['exhibit_id'], unique=False)
    op.create_table('exhibit_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exhibit_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='mediatype'), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibit_media_exhibit_id'), 'exhibit_media', ['exhibit_id'], unique=False)
    op.create_table('exhibit_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exhibit_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Enum('uz', 'ru', 'en', name='languagecode'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibit_translations_exhibit_id'), 'exhibit_translations', ['exhibit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exhibit_translations_exhibit_id'), table_name='exhibit_translations')
    op.drop_table('exhibit_translations')
    op.drop_index(op.f('ix_exhibit_media_exhibit_id'), table_name='exhibit_media')
    op.drop_table('exhibit_media')
    op.drop_index(op.f('ix_exhibit_audio_tracks_exhibit_id'), table_name='exhibit_audio_tracks')
    op.drop_table('exhibit_audio_tracks')
    op.drop_index(op.f('ix_exhibits_slug'), table_name='exhibits')
    op.drop_index(op.f('ix_exhibits_museum_id'), table_name='exhibits')
    op.drop_index(op.f('ix_exhibits_hall_id'), table_name='exhibits')
    op.drop_table('exhibits')
    # ### end Alembic commands ###
